### ISSUE TITLE
PassDrop stopped working - Dropbox v1 API disabled

### ISSUE THREAD

**Issue by chadaustin** [chadaustin/passdrop#1]
Filing a tracking bug so I can report the progress I've made on updating PassDrop to Dropbox's V2 API.  Sorry for the delays everyone!

**Comment by chadaustin** [comment]
The latest github master is upgraded to SwiftyDropbox and the Dropbox browser view seems to be running okay.  Also, once you add a database, it can read databases.

I need to test editing (though I've actually never used that feature), database creation, and update the dropbox browsing UI to sort the files.

**Comment by robertyoung319** [comment]
WHen will we see progress on this serious problem

**Comment by chadaustin** [comment]
Sorting directory contents is working, but I'm looking into why database creation is failing with an error.

I suspect there's only a little bit of programming remaining.  Mostly I have to manually test.  When I have a TestFlight build up, I can invite anyone who's interested to help manually test.

**Comment by chadaustin** [comment]
OK, the code seems to work, and now I'm trying to figure out why my apple developer signing stuff isn't working... Once that's done I can send out test builds!

**Comment by chadaustin** [comment]
I just released version 2.0.2 which updates the app to Dropbox API v2.  I believe there are a few crashes that might occur in the app but I won't have time to investigate them until perhaps this weekend, so I figured there's no harm in releasing this update as it stands.  Now you can at least access your passwords.  :)

Let me know if you have any problems!

**Comment by tihonich** [comment]
@chadaustin great thanks for your work! 

I have checked 2.02 based on iOS 11.0.3 and have got folowing results:
1.  Openning database with extension *.dbx works is ok
2.  Openning database with extension *.kdbx returns error **"There was an error loading the database"**

Could you please fix code for extension *.kdbx? Is it possible or better to use *.dbx yet?

Great thanks! Have you good and fruitful weekend!

**Comment by robertyoung319** [comment]
I am successfully opening .kdb databases with 2.02

**Comment by ScottRJohnson** [comment]
So awesome to see you updating this tool! One question-- is the code truly not compatible with iOS 8 any more or did the setting just get updated because xCode? My main carry is stuck on iOS 8 until I can find a job...
Thanks for the update!

**Comment by chadaustin** [comment]
@tihonich Is kdbx the KeePass 2 format?  If so, PassDrop doesn't support it since it's an entirely different file format as far as I understand.  It might be a good project for someone to try to add KeePass 2 database support.

I personally use KeePassX and the v1 format an all of my devices.

**Comment by chadaustin** [comment]
@ScottRJohnson I tried to preserve iOS 8.0 support but SwiftyDropbox, the Swift library for Dropbox v2 only supports iOS 9.0 and up.  Do you have an iPhone 4?

cc @scobbe @wkiefer How plausible is it to get SwiftyDropbox running on iOS 8.0?

**Comment by chadaustin** [comment]
I am currently uploading build 2.0.3 which fixes a crash on iPhone when linking Dropbox and when switching between apps.  Hopefully it will be available within a week!

**Comment by scobbe** [comment]
Our auth flow depends on being rendered in a safari view controller, not a regular web view, and it's only available in iOS 9

**Comment by chadaustin** [comment]
@scobbe Thanks for your fast response!

**Comment by tihonich** [comment]
@chadaustin you are right  kdbx is the KeePass 2 format. I see that it is not supported but I hope that it will be inlclude in the future. Thanks.

**Comment by ScottRJohnson** [comment]
@chadaustin @scobbe Wow, thanks for your quick response!  

I'm actually running a 4s, which can run iOS 9, but doing it pretty much makes the phone so incredibly unstable and slow that it basically bricks it.  I don't know why Apple even bothers, they obviously didn't QA it at all.

Simple answer is to get a paying job and drop some coin on those smooth, smooth iPhone X curves.  I'm so sick of ancient hardware...

Thanks again!

**Comment by chadaustin** [comment]
I'm going to call this one done - if you run into any issues with the new Dropbox API, let me know!
