### ISSUE TITLE
Groups messed up

### ISSUE THREAD

**Issue by VauxhallViva** [chadaustin/passdrop#2]
Hi,

Love this app, but after updating to your V2 version I have issues accessing my entries in my database. My two main groups are almost empty (just a few entries), and I have a third group called "Backup" where I can find all entries (from my two main groups).

Let me know if I can provide you with any more details.

/Leif

**Comment by chadaustin** [comment]
Hm.  Have you tried loading the password database with keepassx on a desktop computer?  Does it show the full results?  Can you look at the change history for the file in Dropbox and see if it got changed somehow?

I'm not familiar with the kdb file format at all so don't have an explanation.  @rudism any guesses?

**Comment by VauxhallViva** [comment]
I tried just now to open it up in KeepassX 0.4.4, and it looked fine, contents in groups were correct. Normally I use the "official" Keepass application (ver 1.x) on Windows to maintain the database.

**Comment by jasmeralia** [comment]
Same here, I have like Personal > Games which shows under Backup > Games, or Personal > Social > Instant Messagers, which shows as Backup > Hosting > Instant Messagers. Looks fine on my pc with KeePass 1.X as well as the Android app KeePassMob. Things definitely are in wrong places for the hierarchies. (This also didn't happen with the original Passdrop app that broke with ios 11.)

**Comment by chadaustin** [comment]
Thanks for the report.  I don't observe this particular issue.  It would be easy to debug if I had access to your password database but that's obviously not a good idea.  😞 

I'm wondering if it's perhaps a 32-bit vs. 64-bit compatibility issue?  The original PassDrop was 32-bit, and I see some 64-bit compatibility warnings in the build output...  I can try to fix them but I can't guarantee that would have any effect.

Are either of you handy with Xcode?  Maybe you can run the app on your phone in a debugger and we can try to debug where the groups and passwords are getting put in the wrong places?

**Comment by VauxhallViva** [comment]
I have used XCode occasionally, so could maybe try some debugging if you point me in the right direction with a small guide.

**Comment by robbve** [comment]
I am having the same issue.  My groups on PassDrop2 do NOT reflect the groups that I have in the Desktop version.  This problem is very limiting, as one of the groups that no longer appears in my PassDrop2 is my most used and I cannot access it on my phone! I am using KeePass 1.34 on 2 different Windows Boxes. and the latest PassDrop as downloaded from Apple AppStore.  I am not a developer (but I am a SW prod manager), so I may be limited in helping with troubleshooting.  But I am willing to help where I can!  As If this can't be fixed, I will need to find a new solution.
If you edit on PassDrop and Sync, then it corrupts the .kdb file and the incorrect grouping does showup on the desktop version.

**Comment by chadaustin** [comment]
Kai Fischer sent me what looks like a plausible repro path in my email, but I have not yet had time to try it.  I don't think I'll have time tomorrow either.  But this weekend I'll try to take a shot at it.

@VauxhallViva I'll give a little bit of a guide in case you have time to look before I do:

- First run `https://github.com/chadaustin/passdrop.git` from the terminal.
- If you don't have CocoaPods installed, install it with `sudo gem install cocoapods`
- Then `cd passdrop` and run `pod install`.

Now open the xcworkspace file (I forget the name, but it should be visible in the directory) in Xcode, plug in your iOS device, select it in the dropdown in the upper left, and press Command-R.

I'd personally set a breakpoint in https://github.com/chadaustin/passdrop/blob/master/Classes/KdbReader.m#L90 to see what the KDB data looks like before it's displayed in the frontend UI.  That would let us know whether the KDB library is reading it incorrectly or if there's something at the UI layer that's not showing stuff correctly.

**Comment by chadaustin** [comment]
Actually, there is a way that you could help.  If someone could make a fake password database that exhibits the problem, that would help.  My own password databases show correctly in PassDrop 2.

**Comment by chadaustin** [comment]
OK, I tried to reproduce this today by creating password databases with various groups, but I couldn't reproduce the issue.  Would somebody be able to share with me a new password database that illustrates the problem?

Part of me wonders if it's an issue with 32-bit phones.  What devices are you witnessing this issue on?

**Comment by VauxhallViva** [comment]
I did not have time yet to do any tests or debugging, unfortunately. What I can inform you is that I am using an iPhone 7 with iOS 11.0.3, so I don't think it's a 32-bit issue?

As a first step, I thought I would play around with a new database and see if I can replicate the issue and then send you that database. Getting time for a XCode session is a bit difficult for me right now, but as soon as time permits I will try, if the problem is not resolved until then.

**Comment by VauxhallViva** [comment]
OK, managed to replicate the problem now with a fresh database that I created in KeePass 1.33 on Windows. Added two main groups and 5 sub-groups, and some random entries in each sub-group. When opening on the phone, I see the two main groups, but one is empty and the other one has two sub-groups, one of the coming from the other main group. No backup folder involved in this case, but groups definitely messed up.

I have added the database file, as well as some screenshots with the correct group layout and entries, as well as two screenshots from my phone where you see something else. Password is also in that ZIP archive.

Hope this helps!

[test_database.zip](https://github.com/chadaustin/passdrop/files/1406589/test_database.zip)

**Comment by robbve** [comment]
I'm using 9.3.x on a iPhone 6,  Keepass 1.34 on a Windows 10 & Windows 7
boxes.

~Robb

Robb S. Van Eman
Chief Product Officer
AgEx, Inc.

+1.512.484.3090 (m)

**Comment by jasmeralia** [comment]
Using an iPhone 7. If I have time today I'll save a redacted copy on my
database and attach it.

**Comment by chadaustin** [comment]
Hello all,

Kai sent me a fake database that helped me reproduce the issue.  I now see the bug and am working on a fix but it isn't quite done.  Hopefully this week I can get an updated build out.

Thanks for your patience!

**Comment by chadaustin** [comment]
Status update: spent last night working on moving the sorting code elsewhere.  Made progress, still don't have it working yet.

**Comment by chadaustin** [comment]
Build 2.0.6 was just approved in the app store, so it should be available on your phones soon.  It ought to address the issue with the missing entries and groups.  Let me know how it goes!

**Comment by VauxhallViva** [comment]
That was good news indeed! The new build is not available for me yet, but will report back as soon as I can install it.

**Comment by robbve** [comment]
I have 2.0.3, and don't see..6 yet.  I'll test it as soon as I get it.

Thanx for getting on this!

~Robb

Robb S. Van Eman
Chief Product Officer
AgEx, Inc.

+1.512.484.3090 (m)

**Comment by jasmeralia** [comment]
Likewise, I'm on 2.0.4, don't see .6 yet but will keep an eye out for it
and report back once I get it.

**Comment by VauxhallViva** [comment]
Ok, it’s available now and it seems to work fine! Many thanks for the quick fix chadaustin!

**Comment by chadaustin** [comment]
OK, I think this is done!  Let me know if you run into more problems with PassDrop.
